name: Build and Deploy GroomingReminderBot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GroomingReminderBot
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: GroomingReminderBot

      - name: Deploy to Remote Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.jar"
          target: "~/GroomingReminderBot/"

      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop the application using shutdown.sh
            if [ -f ~/GroomingReminderBot/shutdown.sh ]; then
              echo "Stopping the application..."
              ~/GroomingReminderBot/shutdown.sh
            else
              echo "shutdown.sh not found, skipping shutdown."
            fi
            
            # Start the application using start.sh
            if [ -f ~/GroomingReminderBot/start.sh ]; then
              echo "Starting the application..."
              ~/GroomingReminderBot/start.sh
            else
              echo "start.sh not found, skipping startup."
            fi