name: Build and Deploy GroomingReminderBot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GroomingReminderBot
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: GroomingReminderBot

      - name: Deploy to Remote Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*.jar"
          target: "~/GroomingReminderBot/"

      - name: Restart Application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -f ~/GroomingReminderBot/app.pid ]; then
              kill $(cat ~/GroomingReminderBot/app.pid) || true
              rm ~/GroomingReminderBot/app.pid
            fi
            nohup java -jar ~/GroomingReminderBot/*.jar > ~/GroomingReminderBot/app.log 2>&1 & echo $! > ~/GroomingReminderBot/app.pid